### ISSUE TITLE
403 Forbidden Error using axios or node-fetch for Unreal Marketplace Home API

### ISSUE THREAD

**Issue by GauravDe-git** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#296]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

GET

### What is the Request URL?

https://www.unrealengine.com/marketplace/api/homeData

### What is the Response Status Code?

Status Code 403

### Additional Context (if applicable)

P.S. Sorry if my issue sounds dumb, as Im still kinda new at this but
The get request is not working even though the json data opens perfectly fine in a browser window..
Creating a simple axios test script like
```const axios = require('axios');

const url = 'https://www.unrealengine.com/marketplace/api/homeData';

axios.get(url)
  .then(response => {
    console.log(response.data);
  })
  .catch(error => {
    console.error('Error fetching data:', error);
  });
``` 
gives the errors in console-
```Error fetching data: AxiosError: Request failed with status code 403
    at settle (C:\Users\gmgau\OneDrive\Desktop\test\node_modules\axios\dist\node\axios.cjs:2015:12)
    at BrotliDecompress.handleStreamEnd (C:\Users\gmgau\OneDrive\Desktop\test\node_modules\axios\dist\node\axios.cjs:3131:11)
    at BrotliDecompress.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Users\gmgau\OneDrive\Desktop\test\node_modules\axios\dist\node\axios.cjs:4262:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.3',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://www.unrealengine.com/marketplace/api/homeData',
    data: undefined
  },
  ```
  and so on...

**Comment by LeleDerGrasshalmi** [comment]
you are facing cloudflare anti bot protection, not much you can, maybe try using a browser-like user-agent.
